In [1]:

class Employee:

   # Creating a data member to count the number of Employees

   no_of_employees = 0
   # Initializing name, family, salary, department

   def __init__(self, name, family_name, salary, department):
       self.__name = name
       self.__family_name = family_name
       self.salary = salary
       self.__department = department
       Employee.no_of_employees += 1
    #Creating a function to average salary
   @staticmethod
   def average_salary(employees):

       sum = 0
       for employee in employees:
           sum += employee.salary
       return sum / Employee.no_of_employees
     #Creating a Fulltime Employee class
class FulltimeEmployee(Employee):

   def __init__(self, name, family_name, salary, department):
       super().__init__(name, family_name, salary, department)

   def full_time_benefits(self):
       print("Few benefits as full time employee.")

# Creating the instances of Fulltime Employee class and Employee class and also calling their member functions.

def main():
   employees = []
   fte1 = FulltimeEmployee("Employee1", "FamilyName1", 120000, "Management")
   fte1.full_time_benefits()
   employees.append(fte1)
   fte2 = FulltimeEmployee("Employee2", "FamilyName2", 180000, "RnD")
   employees.append(fte2)
   emp1 = Employee("Employee3", "FamilyName3", 160000, "Marketing")
   employees.append(emp1)
   emp2 = Employee("Employee4", "FamilyName4", 135000, "HR")
   employees.append(emp2)
   print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
   main()

Few benefits as full time employee.
Average salary: 148750.0


In [2]:
import numpy as np

                                  #Creating a random vector of size 20
v = np.random.uniform(1, 20, 20)

v = v. reshape(4, 5)  # Reshape the array to 4 by 5

print(v)

v[np.arange(4), v.argmax(axis=1)]=0 # Replace the max value with 0 (axis=1)
print(v)


[[13.4960626   8.70050601 19.28670533  3.0825038   9.69304276]
 [19.19052563  7.10010313 14.77794658 15.40002458 16.62925316]
 [ 9.71311024  4.31510479 18.59838564  9.30946578  5.63517183]
 [16.74718431 12.28881945 11.26566346 12.30962606  4.52363408]]
[[13.4960626   8.70050601  0.          3.0825038   9.69304276]
 [ 0.          7.10010313 14.77794658 15.40002458 16.62925316]
 [ 9.71311024  4.31510479  0.          9.30946578  5.63517183]
 [ 0.         12.28881945 11.26566346 12.30962606  4.52363408]]
